
\c postgres
drop database clients ;
create database clients ;
\c clients



CREATE TABLE clients (
	cl_nom varchar(20) PRIMARY KEY ,
	cl_adresse text
) ;

CREATE TABLE contacts (
	ct_nom text,
	ct_prenom text,
	ct_telephone text,
	ct_email text,
	ct_fonction text,
	cl_nom text REFERENCES clients ( cl_nom )
) ;

CREATE TABLE prestations (
	prest_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--	prest_id serial PRIMARY KEY,
        prest_intitule text,
	prest_description text ,
	prest_type text,
	prest_date_debut timestamptz,
	prest_date_fin timestamptz,
	prest_confirm boolean,
	cl_nom text REFERENCES clients ( cl_nom )
) ;

CREATE TABLE factures (
	fact_num text primary key ,
	fact_date timestamptz,
	fact_date_paiement timestamptz,
	fact_moyen_paiement text,
	cl_nom text references clients ( cl_nom )
) ;

CREATE TABLE lignes_factures (
	fact_num text REFERENCES factures ( fact_num ) ,
	prest_id integer UNIQUE REFERENCES prestations ( prest_id ),
	lf_intitule text,
	lf_montant numeric(10,3),
	lf_qte numeric ,
        PRIMARY KEY ( fact_num, prest_id )
) ;


-- Production d'un jeu de données
\i db_clients_data.sql


CREATE OR REPLACE VIEW factview AS
	SELECT f.fact_num, f.fact_date, f.fact_date_paiement, f.cl_nom,
		sum(l.lf_montant * l.lf_qte) as montant_HT -- ,
		FROM factures f JOIN lignes_factures l USING ( fact_num )
			LEFT JOIN prestations p USING (prest_id)
                GROUP BY f.fact_num, f.fact_date, f.fact_date_paiement, f.cl_nom
		ORDER BY substring(fact_num from '..$') ASC ;


CREATE INDEX prest_date_idx ON prestations ( prest_date_debut , prest_date_fin  )  ;

CREATE INDEX prest_date_deb_idx ON prestations ( prest_date_debut ) WHERE prest_confirm ;

CREATE MATERIALIZED VIEW facturation AS
	SELECT f.fact_num, f.fact_date, f.fact_date_paiement, f.cl_nom,
		sum(l.lf_montant * l.lf_qte) as montant_HT -- ,
		FROM factures f JOIN lignes_factures l USING ( fact_num )
                LEFT JOIN prestations p ON l.prest_id=p.prest_id
                GROUP BY f.fact_num, f.fact_date, f.fact_date_paiement, f.cl_nom
		ORDER BY substring(fact_num from '..$') ASC ;


-- \i db_clients_table_formations.sql

-- \i db_clients_alter.sql

-- VACUUM ANALYSE;
